### ISSUE TITLE
InteractiveMediaConfirm - AttributeError: Assignment not allowed to composite field "text" in protocol message object.

### ISSUE THREAD

**Issue by webngt** [dialogs/python-bot-sdk#32]
here we have problem with InteractiveMediaConfirm

```python
confirm = InteractiveMediaConfirm("а", "b", "ok", "dismiss")

    button1 = interactive_media.InteractiveMediaButton("Button", "button")

    bot.messaging.send_message(

        private_peer(params[0].sender_uid), "text", [InteractiveMediaGroup([InteractiveMedia(1, button1, 'default', confirm)])]

    )
```

```
Traceback (most recent call last):

  File "C:/Users/xxx-xx-xxxxx/PycharmProjects/python-bot-sdk/dialog_bot_sdk/examples/echobot.py", line 76, in <module>

    bot.messaging.on_message(on_msg, on_click)

  File "C:\Users\xxx-xx-xxxxx\PycharmProjects\python-bot-sdk\dialog_bot_sdk\messaging.py", line 144, in on_message

    callback(up.updateMessage)

  File "C:/Users/xxx-xx-xxxxx/PycharmProjects/python-bot-sdk/dialog_bot_sdk/examples/echobot.py", line 21, in on_msg

    private_peer(params[0].sender_uid), "text", [InteractiveMediaGroup([InteractiveMedia(1, button1, 'default', confirm)])]

  File "C:\Users\xxx-xx-xxxxx\PycharmProjects\python-bot-sdk\dialog_bot_sdk\messaging.py", line 36, in send_message

    g.render(media)

  File "C:\Users\xxx-xx-xxxxx\PycharmProjects\python-bot-sdk\dialog_bot_sdk\interactive_media.py", line 134, in render

    action.render(act)

  File "C:\Users\xxx-xx-xxxxx\PycharmProjects\python-bot-sdk\dialog_bot_sdk\interactive_media.py", line 109, in render

    target.confirm = self.confirm.render()

  File "C:\Users\xxx-xx-xxxxx\PycharmProjects\python-bot-sdk\dialog_bot_sdk\interactive_media.py", line 67, in render

    confirm.text = wrappers_pb2.StringValue(value=self.text)

  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 724, in setter

    '"%s" in protocol message object.' % proto_field_name)

AttributeError: Assignment not allowed to composite field "text" in protocol message object.
```

**Comment by Drymonade** [comment]
Fixed this in lib.
