### ISSUE TITLE
GOAWAY message

### ISSUE THREAD

**Issue by geon071** [dialogs/python-bot-sdk#33]
After doing nothing, about two minutes, bot receive message "goaway" and app exit with error:
Traceback (most recent call last):

  File "/python-bot-sdk/dialog_bot_sdk/examples/echobot.py", line 94, in <module>

    bot.messaging.on_message(on_msg, on_click)

  File "\python-bot-sdk\dialog_bot_sdk\messaging.py", line 139, in on_message

    for update in self.internal.updates.SeqUpdates(empty_pb2.Empty()):

  File "\Anaconda3\lib\site-packages\grpc\_channel.py", line 364, in __next__

    return self._next()

  File "\Anaconda3\lib\site-packages\grpc\_channel.py", line 358, in _next

    raise self

grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:

                status = StatusCode.INTERNAL

                details = "GOAWAY received"

                debug_error_string = "{"created":"@1551343714.160000000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"GOAWAY received","grpc_status":13}"

If bot working (receive message, send text etc) it all good.

**Comment by Drymonade** [comment]
Fixed this in ``1.3.1`` version.
