### ISSUE TITLE
Error "LICENSE file not found" during DialogBot pip3 install

### ISSUE THREAD

**Issue by pabloli84** [dialogs/python-bot-sdk#63]
Hello,

During DialogBot installation via pip3 getting this error:

```
pip3 install DialogBot                                                                                                              
Collecting DialogBot
  Using cached dialogbot-0.0.4.tar.gz (13.1 MB)
    ERROR: Command errored out with exit status 1:
     command: /.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/g2/9ls_yb4n4lg373clb5w9__p80000gn/T/pip-install-ddugxr9m/dialogbot_3f4ecae54029478eb3d1101d7eca3726/setup.py'"'"'; __file__='"'"'/private/var/folders/g2/9ls_yb4n4lg373clb5w9__p80000gn/T/pip-install-ddugxr9m/dialogbot_3f4ecae54029478eb3d1101d7eca3726/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/g2/9ls_yb4n4lg373clb5w9__p80000gn/T/pip-pip-egg-info-y59md4pu
         cwd: /private/var/folders/g2/9ls_yb4n4lg373clb5w9__p80000gn/T/pip-install-ddugxr9m/dialogbot_3f4ecae54029478eb3d1101d7eca3726/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/g2/9ls_yb4n4lg373clb5w9__p80000gn/T/pip-install-ddugxr9m/dialogbot_3f4ecae54029478eb3d1101d7eca3726/setup.py", line 20, in <module>
        with open('LICENSE', 'r', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**OS:** MacOS X 10.15.7
**Python version:** 3.8

**Comment by pabloli84** [comment]
Seems I was using not correct package name, it should be dialog_bot_sdk instead of dialogbot.
